version: "3"
services:
  web:
    build: .
    image: quanbrew/play_trpg_bot
    command: ./start.sh
    restart: always
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
    ports:
      - "127.0.0.1:8880:8880"
    environment:
      - PYTHONPATH=/code
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    restart: always
    env_file:
      - .env
  redis:
    image: redis
    restart: always
    volumes:
      - ./data/redis:/data
  bot:
    build: .
    image: quanbrew/play_trpg_bot
    command: python bot.py
    restart: always
    ports:
      - "127.0.0.1:9990:9990"
    depends_on:
      - db
      - redis
    env_file:
      - .env
    volumes:
      - .:/code
  touzi:
    build: .
    image: quanbrew/play_trpg_bot
    command: python touzi_bot.py
    ports:
      - "127.0.0.1:9991:9991"
    restart: always
    env_file:
      - .env
    volumes:
      - .:/code