# Generated by Django 2.1.3 on 2019-02-22 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('chat_id', models.IntegerField(primary_key=True, serialize=False)),
                ('counter', models.IntegerField(default=0)),
                ('message_id', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='actor',
            name='belong',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Round'),
        ),
    ]
