# Generated by Django 2.1.3 on 2019-02-22 15:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='chat_id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='round',
            name='message_id',
            field=models.BigIntegerField(),
        ),
    ]
