# Generated by Django 2.2.1 on 2019-05-20 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_round_round_counter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_name', models.CharField(max_length=128)),
                ('is_gm', models.BooleanField(default=False)),
                ('temp_character_name', models.CharField(blank=True, default='', max_length=128)),
                ('chat_id', models.BigIntegerField(db_index=True)),
                ('user_id', models.BigIntegerField(db_index=True)),
                ('full_name', models.CharField(max_length=256)),
                ('username', models.CharField(blank=True, default='', max_length=128)),
            ],
        ),
    ]
