# Generated by Django 2.2.1 on 2019-05-22 19:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_variable'),
    ]

    operations = [
        migrations.AddField(
            model_name='variable',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variable',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
