# Generated by Django 2.1.3 on 2019-01-17 16:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('archive', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
