# Generated by Django 2.1.3 on 2019-01-17 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('archive', '0002_auto_20190117_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='archive.Chat'),
        ),
    ]
