# Generated by Django 2.1.3 on 2019-01-28 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('archive', '0003_auto_20190117_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='archive.Log'),
        ),
    ]
