# Generated by Django 2.1.3 on 2019-02-21 10:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('archive', '0004_auto_20190128_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='password',
            field=models.CharField(default='', max_length=512),
        ),
    ]
