# Generated by Django 2.2.1 on 2019-05-20 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0006_auto_20190506_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='default_dice_face',
            field=models.IntegerField(default=20),
        ),
    ]
