# Generated by Django 2.2.1 on 2019-05-23 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0007_chat_default_dice_face'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='kind',
            field=models.IntegerField(choices=[(1, 'NORMAL'), (2, 'DICE'), (3, 'DESC'), (4, 'SYSTEM'), (5, 'ME'), (6, 'ROLL'), (7, 'HIDE_DICE'), (8, 'VARIABLE')], default=1),
        ),
    ]
