# Generated by Django 2.2.1 on 2019-05-31 14:54

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0008_auto_20190523_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='entities',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[]),
            preserve_default=False,
        ),
    ]
