# Generated by Django 2.2.3 on 2019-07-11 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0009_log_entities'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='temp_character_name',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='log',
            name='kind',
            field=models.IntegerField(choices=[(1, 'NORMAL'), (2, 'DICE'), (3, 'DESC'), (4, 'SYSTEM'), (5, 'ME'), (6, 'ROLL'), (7, 'HIDE_DICE'), (8, 'VARIABLE'), (9, 'DIVIDER')], default=1),
        ),
        migrations.AlterField(
            model_name='log',
            name='reply',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='archive.Log'),
        ),
    ]
