# Generated by Django 2.2.3 on 2019-07-11 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0010_auto_20190711_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='source_message_id',
            field=models.BigIntegerField(db_index=True, default=None, null=True, verbose_name='Source Message ID'),
        ),
        migrations.AlterField(
            model_name='log',
            name='message_id',
            field=models.BigIntegerField(db_index=True, verbose_name='Message ID'),
        ),
    ]
