# Generated by Django 2.2.3 on 2019-07-11 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0011_auto_20190711_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='gm_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chat',
            name='gm_mode_notice',
            field=models.BigIntegerField(default=None, null=True),
        ),
    ]
