# Generated by Django 2.2.3 on 2019-07-22 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0012_auto_20190711_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
