# Generated by Django 2.2.3 on 2019-07-25 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0013_chat_modified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(db_index=True, verbose_name='Telegram User ID')),
                ('photo_url', models.URLField(null=True, verbose_name='Photo URL')),
                ('username', models.CharField(max_length=128, null=True)),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.AlterField(
            model_name='log',
            name='user_id',
            field=models.BigIntegerField(verbose_name='Telegram User ID'),
        ),
    ]
