# Generated by Django 2.2.3 on 2019-07-26 03:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='telegram', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('telegram_id', models.BigIntegerField(db_index=True, verbose_name='Telegram User ID')),
                ('photo_url', models.URLField(null=True, verbose_name='Photo URL')),
                ('username', models.CharField(max_length=128, null=True)),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
            ],
        ),
    ]
